### ISSUE TITLE
02-run-app

### ISSUE THREAD

**Issue by Nawras67** [Nawras67/simple-fortune-cookie#6]

**Comment by Nawras67** [comment]
start

**Comment by Heank16** [comment]
Install Go on Ubuntu

### 1. Downloading the Go tarball

`wget -c https://storage.googleapis.com/golang/go1.6.linux-amd64.tar.gz -O - | sudo tar -xz -C /usr/local`

### 2. Adjusting the Path Variable

` echo "" >> ~/.profile && echo "export PATH=\$PATH:/usr/local/go/bin" >> ~/.profile`

Save the file, and load the new PATH environment variable into the current shell session:
`source ~/.profile`

### 3. Verifying the Go Installation

```
$ go version
go version go1.6 linux/amd64
```

Source: https://linuxize.com/post/how-to-install-go-on-ubuntu-20-04/

**Comment by Nawras67** [comment]
1. Run `go build .` in backend/frontend
2. Run `go run . > /dev/null 2>&1 & ` in backend/frontend
3. go to port `<ip>:8080` and backend `<ip>:9000/fortunes`

**Comment by Heank16** [comment]
Install Go from Ubuntu repository
`sudo apt  install golang-go`
